# Generated by Django 5.1.3 on 2025-10-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=250)),
                ("option1", models.CharField(max_length=150)),
                ("option2", models.CharField(max_length=150)),
                ("option3", models.CharField(max_length=150)),
                ("option4", models.CharField(max_length=150)),
                ("correct_option", models.CharField(max_length=150)),
            ],
        ),
    ]
